### ISSUE TITLE
Code cleanup and organization requested

### ISSUE THREAD

**Issue by shraiysh** [shraiysh/Squeeze-me#1]
- [x] Remove all binary files and add create a `.gitignore` file
- [ ] Put all source files in src

**Comment by shraiysh** [comment]
The second task is for anyone to submit a pull request.

**Comment by goelp14** [comment]
Hi @shraiysh I would like to help but I am not very experienced at github as I am a first-timer. I have a few questions:

1) What are the source files you are referring to?
2) Are they all the files like 'RandomFileGenerator.java'?
3) To clarify, do you want us to make a new branch 'src' and move those files into it?
4) Are there any contribution policies you would want me to follow?

If it is to just make a new branch and move those files into it I would like to give this a try.

**Comment by shraiysh** [comment]
Hi, @goelp14 I'm glad that you're interested. I'll try to answer your questions in the best possible way.

1.(and 2.) The src files here are the `*.java` files as you mentioned. If you know any standard project structure, go ahead and put the project in that structure. It's your wish.
3. No, I would like you to first fork this repository. Then create a new branch for this issue(in your forked repository), move the source files in a new folder named `src` and submit a pull request.
4. Although I did not follow this earlier, I'll recommend Descriptive and precise commit messages. Squash multiple commits if possible.

Hope it answers your question. Feel free to ask anything.

Cheers

**Comment by goelp14** [comment]
Hi, @shraiysh I submitted a pull request. Hopefully it is to your liking.
